### PR TITLE
fix #363

### LINKED ISSUE #363: textstat_dist(x,y,margin="features") is not working when y in not NULL for some methods
for methods: euclidean, jaccard, eJaccard

### PR DESCRIPTION
**Pull request by HaiyanLW**

### CODE REVIEW

File: R/textstat_simil.R [hunk 1]
```diff
@@ -124,15 +124,15 @@ textstat_simil <- function(x, selection = character(0), n = NULL,
     
     # truncate to n if n is not NULL
     if (!is.null(n))
-        result <- head(result, n)
+        result <- head(as.matrix(result), n)  # result returned by some method is a sparse matrix
```
Comment (kbenoit) [inline R/textstat_simil.R]: Doesn't the `as.matrix()` coerce it to a dense matrix?? I thought we were trying to avoid that.
